# Site settings
title: Realestasia
email: contact@realestasia.com
description: "Access our database of investment properties — starting from USD100k"
baseurl: ""
basecdn: "http://cdn.realestasia.com/"
url: "http://realestasia.com"
twitter_username: realestasia
github_username:  realestasia

# Build settings
markdown: kramdown
permalink: pretty
